//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viagens.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=jebm01\\SQLExpress,1958;Initial Catalog=AgTur;Network Library=dbmssocn" +
            ";Connect Timeout=30;User ID=AgTurAdm;Password=erico-pc")]
        public string AgTurConnectionString {
            get {
                return ((string)(this["AgTurConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=jebm01\\SQLExpress,1958;Initial Catalog=AgTur;Network Library=dbmssocn" +
            ";Connect Timeout=30;User ID=AgTurAdm;Password=erico-pc")]
        public string AgTurConnectionString1 {
            get {
                return ((string)(this["AgTurConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=jebm01\\SQLExpress,1958;Initial Catalog=AgTur;Network Library=dbmssocn" +
            ";Connect Timeout=30;User ID=AgTurAdm;Password=erico-pc")]
        public string AgTurConnectionString2 {
            get {
                return ((string)(this["AgTurConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=jebm01\\SQLExpress,1958;Initial Catalog=AgTur;Network Library=dbmssocn" +
            ";Connect Timeout=30;User ID=AgTurAdm;Password=erico-pc")]
        public string AgTurConnectionString3 {
            get {
                return ((string)(this["AgTurConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=jebm01\\SQLExpress,1958;Initial Catalog=AgTur;Network Library=dbmssocn" +
            ";Connect Timeout=30;User ID=AgTurAdm;Password=erico-pc")]
        public string AgTurConnectionString4 {
            get {
                return ((string)(this["AgTurConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=jebm01\\SQLExpress,1958;Initial Catalog=AgTur;Network Library=dbmssocn" +
            ";Connect Timeout=30;User ID=AgTurAdm;Password=erico-pc")]
        public string AgTurConnectionString5 {
            get {
                return ((string)(this["AgTurConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=jebm01\\SQLExpress,1958;Initial Catalog=AgTur;Network Library=dbmssocn" +
            ";Connect Timeout=30;User ID=AgTurAdm;Password=erico-pc")]
        public string AgTurConnectionString6 {
            get {
                return ((string)(this["AgTurConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=jebm01\\SQLExpress,1958;Initial Catalog=AgTur;Network Library=dbmssocn" +
            ";Connect Timeout=30;User ID=AgTurAdm;Password=erico-pc")]
        public string AgTurConnectionString7 {
            get {
                return ((string)(this["AgTurConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=jebm01\\SQLExpress,1958;Initial Catalog=AgTur;Network Library=dbmssocn" +
            ";Connect Timeout=30;User ID=AgTurAdm;Password=erico-pc")]
        public string AgTurConnectionString8 {
            get {
                return ((string)(this["AgTurConnectionString8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=jebm01\\SQLExpress,1958;Initial Catalog=AgTur;Network Library=dbmssocn" +
            ";Connect Timeout=30;User ID=AgTurAdm;Password=erico-pc")]
        public string AgTurConnectionString9 {
            get {
                return ((string)(this["AgTurConnectionString9"]));
            }
        }
    }
}
