//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viagens.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class SpecialSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SpecialSettings defaultInstance = ((SpecialSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SpecialSettings())));
        
        public static SpecialSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Contratos.ini")]
        public string ArquivoContratos {
            get {
                return ((string)(this["ArquivoContratos"]));
            }
            set {
                this["ArquivoContratos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Contratos")]
        public string DiretorioContratos {
            get {
                return ((string)(this["DiretorioContratos"]));
            }
            set {
                this["DiretorioContratos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sombreamento Claro - Ênfase 1")]
        public string EstiloTabelaImp {
            get {
                return ((string)(this["EstiloTabelaImp"]));
            }
            set {
                this["EstiloTabelaImp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Temp")]
        public string DiretórioTrabalho {
            get {
                return ((string)(this["DiretórioTrabalho"]));
            }
            set {
                this["DiretórioTrabalho"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sombreado Claro - Énfasis 1")]
        public string EstiloTabelaImp2 {
            get {
                return ((string)(this["EstiloTabelaImp2"]));
            }
            set {
                this["EstiloTabelaImp2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tabela com grade 8")]
        public string EstiloTabelaCar {
            get {
                return ((string)(this["EstiloTabelaCar"]));
            }
            set {
                this["EstiloTabelaCar"] = value;
            }
        }
    }
}
